DROP DATABASE IF EXISTS alice_db;
DROP USER IF EXISTS `aliceadmin`@`%`;
CREATE DATABASE IF NOT EXISTS alice_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `aliceadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'secret';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `alice_db`.* TO `aliceadmin`@`%`;
CREATE USER IF NOT EXISTS `aliceuser`@`%` IDENTIFIED WITH mysql_native_password BY 'secret';
GRANT SELECT, INSERT, UPDATE, DELETE ON `alice_db`.* TO `aliceuser`@`%`;